//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shoponline1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public long id { get; set; }
        public string title { get; set; }
        public string content { get; set; }
        public string action { get; set; }
        public Nullable<bool> hide { get; set; }
        public string img { get; set; }
        public string status { get; set; }
        public Nullable<int> order { get; set; }
    }
}
